#!/usr/bin/env bash

#
# Make sure you're on the Play instance
#
# EDIT THE NEXT TWO LINES WITH PRIVATE IPs
# ----------------------------------------
spark_master_private_ip="10.77.57.22"
cassandra_master_private_ip="10.11.188.87"
#

cd ~/bettercare4.me/play
git checkout -- .
git pull origin master
./activator clean play-update-secret stage

echo "Done packaging the application!"
echo "Copying files to Spark cluster and Cassandra master"

# start from a clean spark conf directory
ssh -i ~/spark1-kp.pem root@$spark_master_private_ip 'rm -f /root/spark/conf/*'

scp -i ~/spark1-kp.pem -r target/universal/stage root@$spark_master_private_ip:/root/
scp -i ~/spark1-kp.pem -r data root@$spark_master_private_ip:/root/stage/
scp -i ~/spark1-kp.pem data/spark_prod_conf/* root@$spark_master_private_ip:/root/spark/conf/
scp -i ~/spark1-kp.pem data/spark_prod_conf/masters root@$spark_master_private_ip:/root/spark-ec2/
scp -i ~/spark1-kp.pem data/spark_prod_conf/slaves root@$spark_master_private_ip:/root/spark-ec2/
scp -i ~/cassandra1-kp.pem data/bettercare4me.cql ubuntu@$cassandra_master_private_ip:~/

echo "RSYNC the spark cluster"

# RSYNC the spark cluster
ssh -i ~/spark1-kp.pem root@$spark_master_private_ip '/root/spark-ec2/copy-dir /root/stage'
ssh -i ~/spark1-kp.pem root@$spark_master_private_ip '/root/spark-ec2/copy-dir /root/spark/conf'

echo "Start the Spark cluster"

# Start the spark cluster
ssh -i ~/spark1-kp.pem root@$spark_master_private_ip '/root/spark/sbin/start-all.sh'

echo "Source the Cassandra database"

# Source the Cassandra database
# at the prompt type: "source 'data/bettercare4me.cql'; exit;"
ssh -t -i ~/cassandra1-kp.pem ubuntu@$cassandra_master_private_ip 'cqlsh'

echo "Alright, now start the app!"

sudo -E ./target/universal/stage/bin/bettercare4-me -Dhttp.port=80
